# Site settings
title: blarsa
description: "blarsa - two dudes who used to make music together. Garden Party, Grim Grinning Ghosts remix, Time to Say Goodbye remix, Jónsi Around Us remix, russebuss theme songs"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blarsa.com" # the base hostname & protocol for your site
newgrounds: "http://blarsa.newgrounds.com/"
youtube: "https://youtube.com/user/blarsa/"
license: "http://creativecommons.org/licenses/by-nc-sa/4.0/"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

sass:
  style: :compressed
  precision: 9
