# Site settings
title: blarsa
description: "two dudes who used to make music together"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blarsa.com" # the base hostname & protocol for your site
newgrounds: "http://blarsa.newgrounds.com/"
youtube: "http://youtube.com/blarsa/"
license: "http://creativecommons.org/licenses/by-nc-sa/4.0/"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

sass:
  style: :compressed
  precision: 9
